### ISSUE TITLE
Установить допустимые размеры фото для хранения в хранилище

### ISSUE THREAD

**Issue by ghhbdtn** [poly-team-2023/inspection-web-service#23]
При загрузке фото категорий до ~100Кб все ок, на фотках ~180Кб слетела загрузка, в консоли ошибка с хранилищем

**Comment by ghhbdtn** [comment]
![photo_2023-11-22_23-13-14](https://github.com/poly-team-2023/inspection-web-service/assets/70907611/73afd4e4-56aa-4552-9d35-e2393789030c)

**Comment by tetrade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Исправление бага с сохранением фотографии от пользователя](https://trello.com/c/mLfQvDTd/47-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%B3%D0%B0-%D1%81-%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC-%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%B8-%D0%BE%D1%82-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)
